### ISSUE TITLE
Typescript thing?

### ISSUE THREAD

**Issue by Bartman0** [goodwillpunning/nodejs-sharing-client#13]
Sorry about the vague description. I am new to Typescript but that's what they use in Tableau Connector SDK.
I am trying to create a delta sharing connector for Tableau and I am using this Javascript package to accomplish that.
Problem is that when creating the connector everything work as planned until I either import or require this package.
I have no clue why and I can't deduce where the source of the problem lies.

Might there be any reason why this package may be causing issues when using in Typescript enviroments?

Also, a Tableau connector is essentially a web page with Typescript/Javascript to do its thing, and the console shows this deeply nested stack trace.

The error is at line 41 of memstore.js:

`util.inherits(MemoryCookieStore, Store);`

and the stack trace is:
```
Uncaught TypeError: util.inherits is not a function
    at 2Lnsa.6c1baa97b08bd7df (memstore.js:41:6)
    at newRequire (index.e63b3b5b.js:71:24)
    at localRequire (index.e63b3b5b.js:84:35)
    at 2yy2d.21d22bb892bb7293 (cookie.js:37:25)
    at newRequire (index.e63b3b5b.js:71:24)
    at localRequire (index.e63b3b5b.js:84:35)
    at iMyDQ.f99ee3a45257f86a (cookies.js:3:13)
    at newRequire (index.e63b3b5b.js:71:24)
    at localRequire (index.e63b3b5b.js:84:35)
    at iDDXb.5957cd4242ebf2f2 (index.js:18:15)
    
```

if anybody knows what might be going on, I would appreciate some hints to fix this.
If not, I also settle for some approaches on how to go about this.   ;-)
Google searches haven't resulted in anything that I could apply, let alone use.

Thanks!

**Comment by gustavopedroni** [comment]
This its my "solution":

```typescript

declare module 'delta-sharing' {
  import { DataFrame } from 'danfojs-node'

  // Protocol classes
  export class DeltaSharingProfile {
    static CURRENT: number
    shareCredentialsVersion: number
    endpoint: string
    bearerToken: string
    expirationTime: string | null

    constructor(
      shareCredentialsVersion: number,
      endpoint: string,
      bearerToken: string,
      expirationTime?: string | null,
    )

    static readFromFile(profile: string): DeltaSharingProfile
    static fromJson(json: string | ArrayBuffer): DeltaSharingProfile
    toString(): string
  }

  export class Share {
    shareName: string

    constructor(shareName: string)

    static fromJson(json: string | ArrayBuffer): Share
    toString(): string
  }

  export class Schema {
    schemaName: string
    share: string

    constructor(schemaName: string, share: string)

    static fromJson(json: string | ArrayBuffer): Schema
    toString(): string
  }

  export class Table {
    tableName: string
    share: string
    schema: string

    constructor(tableName: string, share: string, schema: string)

    static fromJson(json: string | ArrayBuffer): Table
    toString(): string
  }

  export class Protocol {
    static CURRENT: number
    minReaderVersion: number

    constructor(minReaderVersion: number)

    static fromJson(json: string | ArrayBuffer): Protocol
    toString(): string
  }

  export class Format {
    provider: string
    options: Record<string, unknown>

    constructor(provider?: string, options?: Record<string, unknown>)

    static fromJson(json: string | ArrayBuffer): Format
    toString(): string
  }

  export class Metadata {
    id: string
    tableName: string
    description: string
    format: Format
    schemaString: string
    partitionColumns: string[]

    constructor(
      id: string,
      tableName?: string,
      description?: string,
      format?: Format,
      schemaString?: string,
      partitionColumns?: string[],
    )

    static fromJson(json: string | ArrayBuffer): Metadata
    toString(): string
  }

  export class AddFile {
    url: string
    id: string
    partitionValues: Record<string, string>
    size: number
    stats: string | null

    constructor(
      url: string,
      id: string,
      partitionValues: Record<string, string>,
      size: number,
      stats?: string | null,
    )

    static fromJson(json: string | ArrayBuffer): AddFile
    toString(): string
  }

  // REST Client Response classes
  export class ListSharesResponse {
    shares: Share[]
    nextPageToken: string | null

    constructor(shares: Share[], nextPageToken: string | null)
    toString(): string
  }

  export class ListSchemasResponse {
    schemas: Schema[]
    nextPageToken: string | null

    constructor(schemas: Schema[], nextPageToken: string | null)
    toString(): string
  }

  export class ListTablesResponse {
    tables: Table[]
    nextPageToken: string | null

    constructor(tables: Table[], nextPageToken: string | null)
    toString(): string
  }

  export class ListAllTablesResponse {
    tables: Table[]
    nextPageToken: string | null

    constructor(tables: Table[], nextPageToken: string | null)
    toString(): string
  }

  export class QueryTableMetadataResponse {
    protocol: Protocol
    metadata: Metadata

    constructor(protocol: Protocol, metadata: Metadata)
    toString(): string
  }

  export class QueryTableVersionResponse {
    deltaTableVersion: number

    constructor(deltaTableVersion: number)
    toString(): string
  }

  export class ListFilesInTableResponse {
    protocol: Protocol
    metadata: Metadata
    addFiles: AddFile[]

    constructor(protocol: Protocol, metadata: Metadata, addFiles: AddFile[])
    toString(): string
  }

  // REST Client
  export class DataSharingRestClient {
    static USER_AGENT: string

    readonly _profile: DeltaSharingProfile
    readonly _numRetries: number

    constructor(
      profile: DeltaSharingProfile,
      numRetries?: number,
      headers?: Record<string, string>,
    )

    listSharesAsync(): Promise<ListSharesResponse>
    listSchemasAsync(
      share: Share,
      maxResults?: number | null,
      pageToken?: string | null,
    ): Promise<ListSchemasResponse>
    listTablesAsync(
      schema: Schema,
      maxResults?: number | null,
      pageToken?: string | null,
    ): Promise<ListTablesResponse>
    listAllTablesAsync(
      share: Share,
      maxResults?: number | null,
      pageToken?: string | null,
    ): Promise<ListAllTablesResponse>
    queryTableMetadataAsync(table: Table): Promise<QueryTableMetadataResponse>
    listFilesInTable(
      table: Table,
      predicateHints?: string[] | null,
      limitHint?: number | null,
    ): Promise<ListFilesInTableResponse>

    static getOrElse<T>(
      json: Record<string, unknown>,
      key: string,
      defaultValue: T,
    ): T
    static clientUserAgent(): string
  }

  // Delta Sharing Reader
  export class DeltaSharingReader {
    constructor(
      table: Table,
      restClient: DataSharingRestClient,
      predicateHints?: string[] | null,
      limit?: number | null,
    )

    table(): Table
    predicateHints(predicateHints: string[]): DeltaSharingReader
    limit(limit?: number | null): DeltaSharingReader
    getEmptyDataFrame(schemaJson: string): DataFrame
    createDataFrame(): Promise<DataFrame>
    getEmptyArray(schemaJson: string): unknown[]
    createDataArray(): Promise<unknown[]>
  }

  // Main Sharing Client
  export class SharingClient {
    readonly _profile: DeltaSharingProfile
    readonly _restClient: DataSharingRestClient

    constructor(profile: DeltaSharingProfile | string)

    listSharesAsync(): Promise<Share[]>
    listSchemasAsync(share: Share): Promise<Schema[]>
    listTablesAsync(schema: Schema): Promise<Table[]>
    listAllTablesAsync(): Promise<Table[]>
  }
}
```
